stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/
build:
  stage: build
  image: "node:17.8.0-bullseye"
  only:
    - /^ci.*$/
    - tags
  script:
    - echo $CI_COMMIT_SHORT_SHA > build-version.txt
    - npm set registry https://registry.npm.taobao.org
    - npm install --progress=false
    - npm run build
    - mv build-version.txt dist/
  artifacts:  
    expire_in: 1 day
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist
deploy-test:
  stage: deploy
  image: "busybox:1.34.1"
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf /disk/nginx/html/laborui/*
    - cp -r ./dist/* /disk/nginx/html/laborui/
  tags:
    - dell
  only:
    - ci-test
deploy-test-win:
  stage: deploy
  image: "busybox:1.34.1"
  variables:
    GIT_STRATEGY: none
  script:
    - rm -r -fo d:/labor/html/laborui/*
    - cp -r ./dist/* d:/labor/html/laborui/
  tags:
    - huawei
    - win
  only:
    - ci-test-win